plugins {
    `java-library`
    id("net.neoforged.moddev").version("2.0.134")
    idea
    id("me.modmuss50.mod-publish-plugin").version("1.1.0")
    id("dev.echoellet.mc-safe-resources") version("0.0.2")
}

val modVersion = gradleProperty("mod_version")
val mcVersion = gradleProperty("minecraft_version")
val neoforgeVersion = gradleProperty("neo_version")
val modId = gradleProperty("mod_id")
val modLoader = "neoforge"
val modGroupId = gradleProperty("mod_group_id")
val epicFightVersion = gradleProperty("epicfight_version")
val epicSkillsVersion = gradleProperty("epicskills_version")

version = modVersion
group = modGroupId

repositories {
    fun strictMaven(name: String, url: String, vararg includeGroups: String) {
        exclusiveContent {
            forRepository { maven { this.name = name; this.url = uri(url) } }
            filter {
                includeGroups.forEach { includeGroup(it) }
            }
        }
    }
    flatDir { dir("libs") }

    strictMaven("CurseForge", "https://cursemaven.com", "curse.maven")
    strictMaven("Modrinth", "https://api.modrinth.com/maven", "maven.modrinth")

    // JEI
    strictMaven("Jared", "https://maven.blamejared.com", "mezz.jei")

    strictMaven("Architectury", "https://maven.architectury.dev", "dev.architectury")

    // KubeJS
    strictMaven("Latvian", "https://maven.latvian.dev/releases", "dev.latvian.mods")

    strictMaven("Iron's Maven - Release", "https://code.redspace.io/releases", "io.redspace")
}

base {
    archivesName = modId
    version = getFullModVersion()
}

fun getFullModVersion(): String = "${modVersion}-mc${mcVersion}-${modLoader}"

java {
    withSourcesJar()

    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

val sourcesJar by tasks.getting(Jar::class)

neoForge {
    version = neoforgeVersion

    parchment {
        mappingsVersion = gradleProperty("parchment_mappings_version")
        minecraftVersion = mcVersion
    }

    runs {
        create("client") {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        create("data") {
            data()
            programArguments.addAll(
                "--mod", modId,
                "--all",
                "--output", file("src/generated/resources/").absolutePath,
                "--existing", file("src/main/resources/").absolutePath
            )
        }

        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        register(modId) {
            sourceSet(sourceSets.main.get())
        }
    }
}

// Include resources generated by NeoForge's data generators.
sourceSets.main {
    resources.srcDir(layout.projectDirectory.dir("src/generated/resources"))
}

configurations {
    val localRuntime by creating

    runtimeClasspath {
        extendsFrom(localRuntime)
    }
}

fun gradleProperty(name: String): String {
    return providers.gradleProperty(name).get()
}

dependencies {
    // NeoForge mod template recommends using this custom "localRuntime" over the standard "runtimeOnly".
    val localRuntime by configurations.getting

    implementation("maven.modrinth:epic-fight:${epicFightVersion}")
    implementation("maven.modrinth:epic-fight-skill-tree:${epicSkillsVersion}")

    // KubeJS compatibility
    compileOnly("dev.latvian.mods:kubejs-neoforge:${gradleProperty("kubejs_version")}")
    compileOnly("dev.latvian.mods:rhino-neoforge:${gradleProperty("rhino_version")}")
    compileOnly("dev.architectury:architectury-neoforge:${gradleProperty("architectury_version")}")

    localRuntime("maven.modrinth:mmmmmmmmmmmm:${gradleProperty("mmmmmmmmmmmm_version")}")

    compileOnly("io.redspace:irons_spellbooks:${gradleProperty("irons_spells_version")}")
}

val generationTaskGroup = "generation"

val generateModMetadata by tasks.registering(ProcessResources::class) {
    group = generationTaskGroup

    val replaceProperties = mapOf(
        "minecraft_version_range" to gradleProperty("minecraft_version_range"),
        "loader_version_range" to gradleProperty("loader_version_range"),
        "mod_id" to modId,
        "mod_version" to modVersion,
        "mod_license" to gradleProperty("mod_license"),
        "mod_name" to gradleProperty("mod_name"),
        "mod_authors" to gradleProperty("mod_authors"),
        "mod_description" to gradleProperty("mod_description"),
    )
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from("src/main/templates")
    into("build/generated/sources/modMetadata")
}

sourceSets.main {
    resources.srcDir(generateModMetadata.map { it.outputs.files.singleFile })
}
neoForge.ideSyncTask(generateModMetadata)

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}

mcSafeResources {
    namespace.set(modId)
}

java.sourceSets.main.get().java.srcDirs(
    tasks.generateLangKeys.map { it.outputs.files.singleFile },
    tasks.generateSoundKeys.map { it.outputs.files.singleFile }
)

tasks.compileJava { dependsOn(tasks.generateLangKeys, tasks.generateSoundKeys) }

fun getCurrentChangelog(): String {
    val changelogFile = project.file("CHANGELOG.md")
    return changelogFile.readText()
}

fun buildReleaseChangelog(changelog: String): String {
    return buildString {
        append(changelog)
        appendLine(); appendLine()
        append(
            """
    ### **Tested against:**
    - **NeoForge:** $neoforgeVersion
    - **Minecraft:** $mcVersion
    - **Epic Fight:** $epicFightVersion
    """.trimIndent()
        )
    }
}

publishMods {
    dryRun.set(false)

    val latestChangelog = getCurrentChangelog()
    val releaseChangelog = buildReleaseChangelog(latestChangelog)
    changelog.set(releaseChangelog)

    modLoaders.add(modLoader)
    type.set(STABLE)
    displayName.set(getFullModVersion())
    file.set(tasks.jar.get().archiveFile)
    additionalFiles.from(sourcesJar)

    curseforge {
        accessToken.set(providers.environmentVariable("CURSEFORGE_API_KEY"))
        projectId.set("1091499")
        minecraftVersions.add(mcVersion)
        projectSlug.set("battle-arts-api")

        requires("epic-fight-mod")
    }

    modrinth {
        accessToken.set(providers.environmentVariable("MODRINTH_API_KEY"))
        projectId.set("7baP43pD")
        minecraftVersions.add(mcVersion)

        requires("epic-fight")

        // Syncs the GitHub README with the Modrinth project description
//        projectDescription.set(
//            providers.fileContents(layout.projectDirectory.file("README.md")).asText
//        )
    }
}

tasks.jar {
    from(rootProject.file("LICENSE.md"))
}
