#Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.cache = true
org.gradle.configuration-cache=true

#Versions
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neoforge_version=21.1.219
neoforge_version_range=[21,)
loader_version_range=[4,)
epicfight_version=21.15.6-mc1.21.1-neoforge
epicskills_version=21.3.1-1.21.1

mod_id=battle_arts_api
display_name=Battle Arts API
license=MIT
group_id=net.forixaim
authors=Forixaim
issue_tracker=https://github.com/Forixaim/Battle-Arts-API/issues
source_code=https://github.com/Forixaim/Battle-Arts-API
display_url=https://github.com/Forixaim/Battle-Arts-API
credits="Me"
description= Go read the main page of this mod on CurseForge.
