#Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#Versions
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.12
forge_version_range=[47,)
loader_version_range=[47,)

#Mod Information
mod_id=battlearts_api
mod_name=Battle Arts API
mod_license=MIT
mod_version=20.14.16.1
mod_group_id=net.forixaim
mod_authors=Forixaim
mod_description=Welcome to the API mod of Battle Arts, currently read CurseForge to know what this does. A full documentation will be in due time.
