[versions]

moddevgradle = "2.0.134"
epic-fight = "21.17.2-mc1.21.1-neoforge"
epicskills = "21.3.1-1.21.1"
modPublish = "1.1.0"

[libraries]

epicFight = { module = "maven.modrinth:epic-fight", version.ref = "epic-fight" }
epicskills = { module = "maven.modrinth:epic-fight-skill-tree", version.ref = "epicskills"}

[plugins]
eclipse = { id = "eclipse"}
idea = { id = "idea"}
javalib = { id = "java-library"}
#Core Gradle Stuff
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
publisher = { id = "me.modmuss50.mod-publish-plugin", version.ref = "modPublish"}
